// A registry row whose "company" name is just a person ("Jeffrey Kyle Porter", "John W Bonner Iv") is a
// sole proprietor licensed in their own name. In the Virginia DPOR backfill 0 of 189 such leads had a
// findable website, versus ~11% of business-named leads, so spending a web search on them is wasted.
// Deliberately conservative: only 2-4 plain name tokens (optional initial / generational suffix) and NO
// business word, "&", digit or punctuation count as an individual.
const BUSINESS_WORD = /\b(inc|llc|l\.l\.c|corp|corporation|company|co|ltd|incorporated|enterprises?|services?|service|contracting|contractors?|construction|electric|electrical|plumbing|heating|cooling|hvac|mechanical|roofing|builders?|homes?|remodeling|renovations?|restoration|group|associates|solutions|systems|brothers|bros|sons|and|repair|maintenance|installation|design|designs|landscap\w*|paving|masonry|concrete|painting|flooring|carpentry|handyman|home|improvements?|industries|international|partners|properties|developments?|exteriors?|interiors?|centers?|centres?|learning|academy|academies|schools?|pre-?schools?|day ?care|child ?care|child|children'?s?|kids?|kiddie|kiddies|tots|tykes|early|education|educational|montessori|nursery|play ?house|play ?school|kindergarten|care|church|ministry|ministries|club|institute|foundation|village|gardens?|house|place|world|land|station|depot|shop|store|clinic|agency|hospice|health|medical|dental|insurance|realty|properties|tow|towing|transport|logistics|freight|septic|pumping|cleaning|bail|bonds|bonding|wealth|management|benefits?|plans?|planning|advisors?|advisory|consult\w*|capital|holdings?|financial|finance|funding|life|lifestyle|seniors|medicare|retirement|annuit\w*|investments?|brokers?|brokerage|alliance|organization|association|assn|assoc|foundation|project|projects|network|global|national|america|american|usa|arizona|oregon|nevada|vegas|head start|start|learners?|learn|learning|prescho\w*|pre-?k|elementary|kidz|kampus|kinder\w*|play\w*|bees|bugs?|bears?|lambs?|sprouts?|sunrays?|hearts?|hands?|dentistry|dentists?|orthodont\w*|animal|animals|pets|vet|veterinary|hospi\w*|wildlife|rescue|rehab\w*|sports?|medicine|therapy|wellness|lodging|motel|inn|hotel|resort|funeral|mortuary|cremation|chapel|memorial|real estate|estate|realty|y m c a|j c c|ymca|jcc|llp|pllc|lp|limited|partnership|trust|fund|family|families|elite|premier|advantage|prosperity|wisdom|adventures?|motorcars?|motors?|auto|brokers|plus|of|at|the|for|with|to|by|from|assurance|insure|ins|ventures?|pioneers?|marketplace|strategies|outlook|risk|savvy|barn|nest|minds?|horizons?|explorers?|skies|sky|mountain|beginnings|success|casa|pups|princess|marketing|tax|accounting|bookkeeping|legacy|smiles|onion)\b/i;
const SUFFIX = new Set(['jr', 'sr', 'ii', 'iii', 'iv', 'v']);

export function looksLikeIndividual(name: string | null | undefined): boolean {
  const n = (name ?? '').trim();
  if (!n || /[&\d,.@/#]/.test(n.replace(/\b[A-Z]\.(?=\s|$)/g, ''))) return false;
  if (BUSINESS_WORD.test(n)) return false;
  const toks = n.split(/\s+/);
  if (toks.length < 2 || toks.length > 5) return false;
  return toks.every((t) => /^[A-Za-z][A-Za-z'’-]*$/.test(t) && (t.length > 1 || toks.indexOf(t) > 0 || true)) && toks.filter((t) => !SUFFIX.has(t.toLowerCase())).length >= 2;
}
