// A registry row whose "company" name is just a person ("Jeffrey Kyle Porter", "John W Bonner Iv") is a
// sole proprietor licensed in their own name. In the Virginia DPOR backfill 0 of 189 such leads had a
// findable website, versus ~11% of business-named leads, so spending a web search on them is wasted.
// Deliberately conservative: only 2-4 plain name tokens (optional initial / generational suffix) and NO
// business word, "&", digit or punctuation count as an individual.
const BUSINESS_WORD = /\b(inc|llc|l\.l\.c|corp|corporation|company|co|ltd|incorporated|enterprises?|services?|service|contracting|contractors?|construction|electric|electrical|plumbing|heating|cooling|hvac|mechanical|roofing|builders?|homes?|remodeling|renovations?|restoration|group|associates|solutions|systems|brothers|bros|sons|and|repair|maintenance|installation|design|designs|landscap\w*|paving|masonry|concrete|painting|flooring|carpentry|handyman|home|improvements?|industries|international|partners|properties|developments?|exteriors?|interiors?|centers?|centres?|learning|academy|academies|schools?|pre-?schools?|day ?care|child ?care|child|children'?s?|kids?|kiddie|kiddies|tots|tykes|early|education|educational|montessori|nursery|play ?house|play ?school|kindergarten|care|church|ministry|ministries|club|institute|foundation|village|gardens?|house|place|world|land|station|depot|shop|store|clinic|agency|hospice|health|medical|dental|insurance|realty|properties|tow|towing|transport|logistics|freight|septic|pumping|cleaning|at|of|the|to|for|in|on|our|my|your|by|with|plus|little|brightpath|sprouts?|nest|stars?|beginnings?|years|friends|angels?|grow|growing|learners?|learn|explorers?|discovery|cradles?|crayons|kidz|enrichment|afterschool|after-school|pre-?k|prek|head ?start|headstart|program|programs|campus|clubhouse|schoolhouse|elementary|preschool|extended|activities|community|army|college|university|city|town|township|county|congregation|temple|parish|archbishop|archdiocese|catholic|diocese|jewish|christian|islamic|baptist|methodist|lutheran|synagogue|yeshiva|organization|association|council|society|league|trust|authority|district|board|department|settlement|youth|action|partnership|network|center|cottage|nursery|garden|buds?|blossoms?|rainbows?|sunshine|sunny|happy|tiny|magic|magical|creative|growing|wonders?|wonderland|adventures?|discover|play|playgroup|playgroups|friends|family|families|kinder|clc|sacc|upk|abcd|mpcc|gan|acorns?|ducklings?|lambs?|bees?|butterflies|butterfly|bunnies|bunny|teddy|rascals?|imagination|treehouse|tree|wee|kidds?|minds?|foundations?|steps|start|success|leading|edge|connections?|corner|baby|babies|alphabet|abc|123|rocking|unicorn|cooperative|co-?op|settlements?|square|one|boces|extension|ymha|ywha|jcc|ymca|ywca|njdcf|dcf|ooe|cdc|pto|pta|technologies|technology|tech)\b/i;
const SUFFIX = new Set(['jr', 'sr', 'ii', 'iii', 'iv', 'v']);

export function looksLikeIndividual(name: string | null | undefined): boolean {
  const n = (name ?? '').trim();
  if (!n || /[&\d,.@/#]/.test(n.replace(/\b[A-Z]\.(?=\s|$)/g, ''))) return false;
  if (BUSINESS_WORD.test(n)) return false;
  const toks = n.split(/\s+/);
  if (toks.length < 2 || toks.length > 5) return false;
  return toks.every((t) => /^[A-Za-z][A-Za-z'’-]*$/.test(t) && (t.length > 1 || toks.indexOf(t) > 0 || true)) && toks.filter((t) => !SUFFIX.has(t.toLowerCase())).length >= 2;
}
